#!/bin/bash

# A firewal that enables connection to Hackers-Arise and,
# no other website on ports 80 and 443

sudo iptables -A OUTPUT -p tcp -d hackers-arise.com -j ACCEPT

sudo iptables -A OUTPUT -p tcp --dport 80 -j DROP

sudo iptables -A OUTPUT -p tcp --dport 443 -j DROP
